# ===============================
# = Hibernate datasource for SQLite
# ===============================
spring:
  datasource: 
#   url: jdbc:sqlite:sqlitesample.db
    url: jdbc:sqlite:src/main/resources/sqliteiib.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
    initialization-mode: always
# ===============================
# = JPA configurations for MySQL
# ===============================
  jpa:
    show-sql: true
    database-platform: crs.fcl.eim.sftp.sqlite.SQLiteDialect
    generate-ddl: true
    hibernate: 
      ddl-auto: none
# ===============================
# = Hibernate datasource for MySQL
# ===============================
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/dbwang
#    username: rwang
#    password: S~168
# ===============================
# = JPA configurations for MySQL
# ===============================
#  jpa:
#    hibernate:
#       ddl-auto: update
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
# ===============================
# = MAIL configurations for smtp.gmail.com
# ===============================
#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    username: hiroyukiwang18@gmail.com
#    password: Genki4Ever
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    protocol: smtp
#    test-connection: false
# ===============================
# = MAIL configurations for smtp.res.ad.crs
# ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.res.ad.crs
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    protocol: smtp
    test-connection: false

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO